apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibc-explorer
  labels:
    app: ibc-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibc-explorer
  template:
    metadata:
      labels:
        app: ibc-explorer
    spec:
      containers:
        - name: ibc-explorer
          image: ghcr.io/polymerdao/ibc-explorer:v0.0.2-alpha-26
          resources:
            limits:
              cpu: '1'
              memory: '2000Mi'
            requests:
              cpu: '1'
              memory: '1000Mi'
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: http://peptide:26657
---
apiVersion: v1
kind: Service
metadata:
  name: ibc-explorer
spec:
  type: LoadBalancer
  selector:
    app: ibc-explorer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000